# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: e_card 
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 4000:3306
    networks:
      - backend


  # Adminer service
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - backend


  # Redis Service   
  redis:
    image: redis 
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - backend

# Networks to be created to facilitate communication between containers
networks:
  e-card:    